name: Run tests

on: pull_request

jobs:
  ci:
    name: Run CI tests
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
      - name: Install dependencies
        run: poetry install
      - name: isort
        run: poetry run isort . --check
      - name: flake8
        run: poetry run flake8 .
      - name: pytest
        run: poetry run pytest .
